Downgrade Rust Container
eclipse-set/build pull request #23
Opened 2023-09-04 09:11 UTC by TruongQuangSB

-Downgrade Rust Container to 1.65
-Change GH container name

2023-09-04 09:14 UTC, TruongQuangSB commented on docker/rust/Dockerfile
> +FROM rust:1.65
Somehow cef-browser doesn't work with rust container version after 1.65

2023-09-04 09:15 UTC, TruongQuangSB commented on docker/rust/Dockerfile
> -RUN rustup target add x86_64-pc-windows-gnu && \
With this version must rust setup move to browser workflows

2023-09-11 09:08 UTC, TruongQuangSB commented
After commit https://github.com/eclipse-set/browser/commit/aad4a68f4956fe521ee810a7e6e02c2d8e2f96f4, we don't need rust container mode

2023-09-11 10:14 UTC, pstuecker requested changes

2023-09-11 10:14 UTC, pstuecker commented on .github/workflows/build-docker-images.yml
>            password: ${{ secrets.GITHUB_TOKEN }}
We can remove the entire workflow here

2023-09-11 10:46 UTC, pstuecker approved these changes

2023-09-11 10:47 UTC, merged